export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const IS_LOGGED_REQUEST = 'IS_LOGGED_REQUEST';
export const IS_LOGGED_SUCCESS = 'IS_LOGGED_SUCCESS';
export const IS_LOGGED_FAILURE = 'IS_LOGGED_FAILURE';

export const ALL_TRACKS_REQUEST = 'TRACKS_REQUEST';
export const ALL_TRACKS_SUCCESS = 'TRACKS_SUCCESS';
export const ALL_TRACKS_FAILURE = 'TRACKS_FAILURE';

export const SHOW_TRACK_REQUEST = 'TRACK_REQUEST';
export const SHOW_TRACK_SUCCESS = 'TRACK_SUCCESS';
export const SHOW_TRACK_FAILURE = 'FETCH_TRACK_FAILURE';

export const CREATE_TRACK_REQUEST = 'CREATE_TRACK_REQUEST';
export const CREATE_TRACK_SUCCESS = 'CREATE_TRACK_SUCCESS';
export const CREATE_TRACK_FAILURE = 'CREATE_TRACK_FAILURE';

export const DELETE_TRACK_REQUEST = 'DELETE_TRACK_REQUEST';
export const DELETE_TRACK_SUCCESS = 'DELETE_TRACK_SUCCESS';
export const DELETE_TRACK_FAILURE = 'DELETE_TRACK_FAILURE';
